
package windows;
import Codificación.ABBTactics;
import Codificación.DatoTactics;
import java.awt.BasicStroke;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.util.LinkedList;
import javax.swing.*;
import java.util.*;


/**
 *
 * @author Armando
 */
public class Interface extends javax.swing.JFrame {
    

    /**
     * Creates new form Interface
     */
    ABBTactics arbol = new ABBTactics();
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
      }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/logo.png"));
        return retValue; 
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        PanelTree = new javax.swing.JPanel();
        ProgramNameLabel = new javax.swing.JLabel();
        branchicon = new javax.swing.JLabel();
        leaf1 = new javax.swing.JLabel();
        leaf2 = new javax.swing.JLabel();
        leaf3 = new javax.swing.JLabel();
        leaf5 = new javax.swing.JLabel();
        leaf6 = new javax.swing.JLabel();
        refreshicon = new javax.swing.JLabel();
        treeicon = new javax.swing.JLabel();
        orderleaf1 = new javax.swing.JLabel();
        orderleaf2 = new javax.swing.JLabel();
        orderleaf3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SalidaTextArea = new javax.swing.JTextArea();
        AyudaButton = new javax.swing.JButton();
        OrderLabel = new javax.swing.JLabel();
        PreordenButton = new javax.swing.JButton();
        InOrdenButton = new javax.swing.JButton();
        PostOrdenButton = new javax.swing.JButton();
        OperacionesLabel = new javax.swing.JLabel();
        IngresarDatoTextField = new javax.swing.JTextField();
        InsertarButton = new javax.swing.JButton();
        EliminarButton = new javax.swing.JButton();
        AleatorioButton = new javax.swing.JButton();
        DeshacerTodoButton = new javax.swing.JButton();
        NúmeroNodosButton = new javax.swing.JButton();
        ActualizarButton = new javax.swing.JButton();
        ÁrbolLabel = new javax.swing.JLabel();
        OrdenamientoLabel = new javax.swing.JLabel();
        JLabelbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABB TOOL");
        setBackground(new java.awt.Color(18, 79, 16));
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(104, 161, 98));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jScrollPane1.setFont(new java.awt.Font("Tw Cen MT", 2, 15)); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(27, 27));

        PanelTree.setBackground(new java.awt.Color(88, 137, 57));
        PanelTree.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        PanelTree.setPreferredSize(new java.awt.Dimension(2200, 2500));

        javax.swing.GroupLayout PanelTreeLayout = new javax.swing.GroupLayout(PanelTree);
        PanelTree.setLayout(PanelTreeLayout);
        PanelTreeLayout.setHorizontalGroup(
            PanelTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2200, Short.MAX_VALUE)
        );
        PanelTreeLayout.setVerticalGroup(
            PanelTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(PanelTree);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1030, 650));

        ProgramNameLabel.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        ProgramNameLabel.setForeground(new java.awt.Color(0, 63, 0));
        ProgramNameLabel.setText("ABB TOOL");
        getContentPane().add(ProgramNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 130, 230, 50));

        branchicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Title.png"))); // NOI18N
        getContentPane().add(branchicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 140, 300, 60));

        leaf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customize button.png"))); // NOI18N
        getContentPane().add(leaf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 340, 50, 50));

        leaf2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customize button.png"))); // NOI18N
        getContentPane().add(leaf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 340, 40, 50));

        leaf3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customize button.png"))); // NOI18N
        getContentPane().add(leaf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 390, 50, 50));

        leaf5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customize button.png"))); // NOI18N
        getContentPane().add(leaf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, 50, 50));

        leaf6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/customize button.png"))); // NOI18N
        getContentPane().add(leaf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 440, 50, 50));

        refreshicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        refreshicon.setMaximumSize(new java.awt.Dimension(40, 40));
        refreshicon.setMinimumSize(new java.awt.Dimension(40, 40));
        refreshicon.setPreferredSize(new java.awt.Dimension(40, 40));
        getContentPane().add(refreshicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 230, 60, 40));

        treeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tree.png"))); // NOI18N
        getContentPane().add(treeicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 70, 60));

        orderleaf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orderleaf.png"))); // NOI18N
        getContentPane().add(orderleaf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, 70, 40));

        orderleaf2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orderleaf.png"))); // NOI18N
        getContentPane().add(orderleaf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 660, 60, 40));

        orderleaf3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orderleaf.png"))); // NOI18N
        getContentPane().add(orderleaf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 710, -1, 40));

        jScrollPane2.setBackground(new java.awt.Color(45, 99, 58));

        SalidaTextArea.setEditable(false);
        SalidaTextArea.setBackground(new java.awt.Color(66, 118, 79));
        SalidaTextArea.setColumns(20);
        SalidaTextArea.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 23)); // NOI18N
        SalidaTextArea.setForeground(new java.awt.Color(255, 255, 255));
        SalidaTextArea.setRows(5);
        jScrollPane2.setViewportView(SalidaTextArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 720, 730, 60));

        AyudaButton.setBackground(new java.awt.Color(131, 176, 114));
        AyudaButton.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        AyudaButton.setForeground(new java.awt.Color(1, 1, 1));
        AyudaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/question mark.png"))); // NOI18N
        AyudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AyudaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 30, 50, 50));

        OrderLabel.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        OrderLabel.setForeground(new java.awt.Color(0, 63, 0));
        OrderLabel.setText("Ordenar");
        getContentPane().add(OrderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 560, 230, 30));

        PreordenButton.setBackground(new java.awt.Color(74, 131, 63));
        PreordenButton.setFont(new java.awt.Font("Tw Cen MT", 1, 21)); // NOI18N
        PreordenButton.setText("  PreOrden");
        PreordenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreordenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PreordenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 610, 160, 40));

        InOrdenButton.setBackground(new java.awt.Color(74, 131, 63));
        InOrdenButton.setFont(new java.awt.Font("Tw Cen MT", 1, 21)); // NOI18N
        InOrdenButton.setText("InOrden");
        InOrdenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InOrdenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InOrdenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 660, 160, 40));

        PostOrdenButton.setBackground(new java.awt.Color(74, 131, 63));
        PostOrdenButton.setFont(new java.awt.Font("Tw Cen MT", 1, 21)); // NOI18N
        PostOrdenButton.setText("  PostOrden");
        PostOrdenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostOrdenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PostOrdenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 710, 160, 40));

        OperacionesLabel.setFont(new java.awt.Font("Vivaldi", 3, 36)); // NOI18N
        OperacionesLabel.setForeground(new java.awt.Color(0, 63, 0));
        OperacionesLabel.setText("Operaciones");
        getContentPane().add(OperacionesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 240, 270, 40));

        IngresarDatoTextField.setBackground(new java.awt.Color(66, 118, 79));
        IngresarDatoTextField.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        IngresarDatoTextField.setForeground(new java.awt.Color(255, 255, 255));
        IngresarDatoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarDatoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(IngresarDatoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 300, 340, 30));

        InsertarButton.setBackground(new java.awt.Color(74, 131, 63));
        InsertarButton.setFont(new java.awt.Font("Tw Cen MT", 1, 21)); // NOI18N
        InsertarButton.setText("    Insertar");
        InsertarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(InsertarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 340, 130, 40));

        EliminarButton.setBackground(new java.awt.Color(74, 131, 63));
        EliminarButton.setFont(new java.awt.Font("Tw Cen MT", 1, 21)); // NOI18N
        EliminarButton.setText("     Eliminar");
        EliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 340, -1, 40));

        AleatorioButton.setBackground(new java.awt.Color(74, 131, 63));
        AleatorioButton.setFont(new java.awt.Font("Tw Cen MT", 1, 21)); // NOI18N
        AleatorioButton.setText("    Generar Árbol Aleatorio");
        AleatorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AleatorioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AleatorioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, 270, 40));

        DeshacerTodoButton.setBackground(new java.awt.Color(74, 131, 63));
        DeshacerTodoButton.setFont(new java.awt.Font("Tw Cen MT", 1, 21)); // NOI18N
        DeshacerTodoButton.setText("    Deshacer Todo");
        DeshacerTodoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeshacerTodoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeshacerTodoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 390, 190, 40));

        NúmeroNodosButton.setBackground(new java.awt.Color(74, 131, 63));
        NúmeroNodosButton.setFont(new java.awt.Font("Tw Cen MT", 1, 21)); // NOI18N
        NúmeroNodosButton.setText("     Número de Nodos");
        NúmeroNodosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NúmeroNodosButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NúmeroNodosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 440, -1, 40));

        ActualizarButton.setBackground(new java.awt.Color(131, 176, 114));
        ActualizarButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 3, 22)); // NOI18N
        ActualizarButton.setText("    Actualizar");
        ActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ActualizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 230, 130, 40));

        ÁrbolLabel.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        ÁrbolLabel.setForeground(new java.awt.Color(0, 63, 0));
        ÁrbolLabel.setText("Árbol");
        getContentPane().add(ÁrbolLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 100, 50));

        OrdenamientoLabel.setFont(new java.awt.Font("Vivaldi", 1, 33)); // NOI18N
        OrdenamientoLabel.setForeground(new java.awt.Color(0, 63, 0));
        OrdenamientoLabel.setText("Ordenamiento Salida:");
        getContentPane().add(OrdenamientoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 360, 30));

        JLabelbackground.setBackground(new java.awt.Color(77, 188, 57));
        JLabelbackground.setFont(new java.awt.Font("Tw Cen MT", 1, 21)); // NOI18N
        JLabelbackground.setForeground(new java.awt.Color(0, 63, 0));
        JLabelbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        getContentPane().add(JLabelbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarDatoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarDatoTextFieldActionPerformed
        try {
            int dato = Integer.parseInt(IngresarDatoTextField.getText());
            IngresarDatoTextField.setText("");
            arbol.insertar(dato, 0);
            paint2(PanelTree.getGraphics());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Insertar el Dato", "¡Alerta!", JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_IngresarDatoTextFieldActionPerformed

    private void AyudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaButtonActionPerformed

        JOptionPane.showMessageDialog (null,"                                                    USO DE LOS BOTONES \n" +"\n" +"\n" +"Botones Especiales\n"+"\n" + " AYUDA (?): Manual para utilizar el programa.\n " +"ACTUALIZAR: Refresca la pantalla cuando se está navagando por el árbol.\n" +"\n" +"Operaciones\n" + "\n" +"INSERTAR: Agrega nodos a la estructura del árbol, que se ingrese en el capturador de datos.\n" +"ELIMINAR: Elimina el nodo objetivo de la estructura del árbol.\n" +"DESHACER TODO: Elimina todo los elementos.\n"+"NÚMERO DE NODOS: Indica la cantidad de nodos que componen el árbol.\n" +"ALTURA DEL ÁRBOL: Muestra el máximo nivel evaluando todo los nodos del árbol.\n" +"GENERAR ÁRBOL ALEATORIO: Crea una estructura árbol de manera aleatoria.\n" +"\n" +"Ordenamientos\n" +"\n" +"PREORDENAR: La secuencia del recorrido se realiza (raíz, izquierdo, derecho).\n" + "INORDEN: La secuencia del recorrido se realiza (izquierdo, raíz, derecho).\n" + "POSTORDEN: La secuencia del recorrido se realiza (izquierdo, derecho, raíz).\n" +"\n" +"\n" +"\n"+"                                                                 CRÉDITOS\n" +"\n" + "                                                ARMANDO ALMENGOR     8-923-936\n" + "                                                ALEXANDER ALMENGOR 8-923-938\n" + "                                                RODOLFO SANDIFORD    3-787-1895\n" + "\n"  + "\n" + "Versión 1.0 ® 2018 "," FAQ",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AyudaButtonActionPerformed

    private void InsertarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarButtonActionPerformed
        try {
            int dato = Integer.parseInt(IngresarDatoTextField.getText());
            IngresarDatoTextField.setText("");
            arbol.insertar(dato, 0);
            paint2(PanelTree.getGraphics());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Tipo de Dato no soportado", "¡Alerta!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_InsertarButtonActionPerformed

    private void InOrdenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InOrdenButtonActionPerformed
         LinkedList rec = new LinkedList();
        arbol.inorden(arbol.getRaiz(), rec);
        String cad = "Inorden:\n";
        for (Object rec1 : rec) {
            cad += rec1 + "  ";
        }
        SalidaTextArea.setText(cad);
    }//GEN-LAST:event_InOrdenButtonActionPerformed

    private void PostOrdenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostOrdenButtonActionPerformed
         LinkedList rec = new LinkedList();
        arbol.postorden(arbol.getRaiz(), rec);
        String cad = "Postorden:\n";
        for (Object rec1 : rec) {
            cad += rec1 + "  ";
        }
        SalidaTextArea.setText(cad);
    }//GEN-LAST:event_PostOrdenButtonActionPerformed

    private void DeshacerTodoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeshacerTodoButtonActionPerformed
        arbol = null;
        arbol = new ABBTactics();
        paint2(PanelTree.getGraphics());
    }//GEN-LAST:event_DeshacerTodoButtonActionPerformed

    private void AleatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AleatorioButtonActionPerformed
       try {
            arbol = new ABBTactics();
            for (int i=0; i<(int)((Math.random()*25)+1); i++){
            int dato = (int)((Math.random()*100)+1);
            arbol.insertar(dato, 1);
            paint2(PanelTree.getGraphics());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Tipo de Dato no soportado", "¡Alerta!", JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_AleatorioButtonActionPerformed

    private void EliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarButtonActionPerformed
       try {
            int dato = Integer.parseInt(IngresarDatoTextField.getText());
            IngresarDatoTextField.setText("");
            arbol.eliminar(dato);      
            paint2(PanelTree.getGraphics());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No Permitido", "¡Alerta!", JOptionPane.WARNING_MESSAGE);
        }  
    }//GEN-LAST:event_EliminarButtonActionPerformed

    private void ActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtonActionPerformed
       paint2(PanelTree.getGraphics());
    }//GEN-LAST:event_ActualizarButtonActionPerformed

    private void PreordenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreordenButtonActionPerformed
        LinkedList rec = new LinkedList();
        arbol.preorden(arbol.getRaiz(), rec);
        String cad = "Preorden:\n";
        for (Object rec1 : rec) {
            cad += rec1 + "  ";
        }
        SalidaTextArea.setText(cad);
    }//GEN-LAST:event_PreordenButtonActionPerformed

    private void NúmeroNodosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NúmeroNodosButtonActionPerformed
       JOptionPane.showMessageDialog(null, "Hay en total " + arbol.getNumNodos() + " nodos en el árbol.");
    }//GEN-LAST:event_NúmeroNodosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JButton AleatorioButton;
    private javax.swing.JButton AyudaButton;
    private javax.swing.JButton DeshacerTodoButton;
    private javax.swing.JButton EliminarButton;
    private javax.swing.JButton InOrdenButton;
    private javax.swing.JTextField IngresarDatoTextField;
    private javax.swing.JButton InsertarButton;
    private javax.swing.JLabel JLabelbackground;
    private javax.swing.JButton NúmeroNodosButton;
    private javax.swing.JLabel OperacionesLabel;
    private javax.swing.JLabel OrdenamientoLabel;
    private javax.swing.JLabel OrderLabel;
    private javax.swing.JPanel PanelTree;
    private javax.swing.JButton PostOrdenButton;
    private javax.swing.JButton PreordenButton;
    private javax.swing.JLabel ProgramNameLabel;
    private javax.swing.JTextArea SalidaTextArea;
    private javax.swing.JLabel branchicon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel leaf1;
    private javax.swing.JLabel leaf2;
    private javax.swing.JLabel leaf3;
    private javax.swing.JLabel leaf5;
    private javax.swing.JLabel leaf6;
    private javax.swing.JLabel orderleaf1;
    private javax.swing.JLabel orderleaf2;
    private javax.swing.JLabel orderleaf3;
    private javax.swing.JLabel refreshicon;
    private javax.swing.JLabel treeicon;
    private javax.swing.JLabel ÁrbolLabel;
    // End of variables declaration//GEN-END:variables
   

    public void paint(Graphics g){
        
        PanelTree.revalidate();
        super.paint(g);
        int X = (getWidth()/5)*arbol.getAltura();
        int X2 = (getWidth()/12);
        int Y = getHeight()/12;
         
         
        //pintaArbol(PanelTree.getGraphics(), arbol.getRaiz(), PanelTree.getWidth()/2, Y, X2, Y,1);     
    }
    
    
    
    private boolean dirty = true;
    private HashMap posicionNodos = new HashMap();
    private HashMap subtreeSizes = new HashMap();
    private Dimension empty = new Dimension(0,0);
    private int parent2child = 30, child2child = 30;
    private FontMetrics fm = null;

public void paint2(Graphics g){
    /*
    PanelTree.removeAll();
    PanelTree.revalidate();
    PanelTree.paint(g);
    int X = (getWidth()/5)*arbol.getAltura();
    int X2 = (getWidth()/12);
    int Y = getHeight()/12;


    pintaArbol(PanelTree.getGraphics(), arbol.getRaiz(), PanelTree.getWidth()/2, Y, X2, Y,1);

    */
    
    
     PanelTree.paint(g);
     fm = g.getFontMetrics();
     calcularPosiciones();
     Graphics2D g2d = (Graphics2D) g;
     g2d.setStroke(new BasicStroke(2.0f));
     g2d.setPaint(Color.white);
     g2d.setBackground(Color.yellow);
     g2d.translate(getWidth() / 2, parent2child);
     dibujarArbol(g2d, this.arbol.getRaiz(), Integer.MAX_VALUE, Integer.MAX_VALUE, fm.getLeading() + fm.getAscent());
     fm = null;


}
 
private void dibujarArbol(Graphics2D g, DatoTactics n, int puntox, int puntoy, int yoffs) 
    {
     if (n == null) 
         return;
     
    //Nodos en forma Elipse (Circunferencia) 
     Ellipse2D.Float r = (Ellipse2D.Float) posicionNodos.get(n);
     
     g.setColor(Color.white);
     g.draw(r);
     
     /*Área de la Elipse 
    
    Ellipse2D.Float r2 = r; 
    Graphics2D g2 = g;
    
    int w = getSize().width;
    int h = getSize().height;
    
    g2.setClip(r2);

    g2.setColor(Color.white);
    g2.fillRect(0, 0, w, h);
    */
    //Datos dentro de los Nodos 
     
     g.setColor(Color.white);
     g.drawString(n.getDato()+ "", r.x + 6, r.y + yoffs+5);
     
     //Aristas del Árbol

     g.setColor(Color.white);
     if (puntox != Integer.MAX_VALUE)
     g.drawLine(puntox, puntoy, (int)(r.x + r.width/2), (int) r.y);
    
     dibujarArbol(g, n.getIzq(), (int)(r.x + r.width/2), (int) (r.y + r.height), yoffs);
     dibujarArbol(g, n.getDer(), (int)(r.x + r.width/2), (int) (r.y + r.height), yoffs);
     
   }

    

    private void calcularPosicion(DatoTactics n, int left, int right, int top) 
    {
      if (n == null) 
          return;
      
      Dimension ld = (Dimension) subtreeSizes.get(n.getIzq());
      if (ld == null) 
          ld = empty;
      
      Dimension rd = (Dimension) subtreeSizes.get(n.getDer());
      if (rd == null) 
          rd = empty;
      
      int center = 0;
      
      if (right != Integer.MAX_VALUE)
          center = right - rd.width - child2child/2;
      else if (left != Integer.MAX_VALUE)
          center = left + ld.width + child2child/2;
      int width = fm.stringWidth(n.getDato()+"");
      
      Ellipse2D.Float r = new Ellipse2D.Float(center - width/2 - 3, top, width + 15, fm.getHeight()+15);
      
      posicionNodos.put(n,r);
      
      calcularPosicion(n.getIzq(), Integer.MAX_VALUE, center - child2child/2, top + fm.getHeight() + parent2child);
      calcularPosicion(n.getDer(), center + child2child/2, Integer.MAX_VALUE, top + fm.getHeight() + parent2child);
    }
    

    private void calcularPosiciones() 
    {
         posicionNodos.clear();
         subtreeSizes.clear();
         DatoTactics root = this.arbol.getRaiz();
         if (root != null) 
         {
             calcularTamañoSubarbol(root);
             calcularPosicion(root, Integer.MAX_VALUE, Integer.MAX_VALUE, 0);
         }
    }
    

    private Dimension calcularTamañoSubarbol(DatoTactics n) 
    {
          if (n == null) 
              return new Dimension(0,0);
 
          Dimension ld = calcularTamañoSubarbol(n.getIzq());
          Dimension rd = calcularTamañoSubarbol(n.getDer());
          
          int h = fm.getHeight() + parent2child + Math.max(ld.height, rd.height);
          int w = ld.width + child2child + rd.width;
          
          Dimension d = new Dimension(w, h);
          subtreeSizes.put(n, d);
          
          return d;
    }
    
    

}